version: "3.3"

services:
    # Rasp gateway (Required: route request to skillsi, register device)
    device-gateway:
        image:  s8sg/device-gateway:1.0.0
        networks:
            - device
            - func_functions # For Dev Environment (should be avoided in production)
        ports:
            - 6107:6107
        environment:
            # Your daily Iot gateway URI
            DAILYIOT: "http://diot-gateway:8080"       
            # A global identification for the device (for example sha of the raspberry pi mac)
            DEVICEID: "${DEVICE_ID}"
            # Device address that is reachable from the platform 
            # (change it to device public url when device not in func_functions)
            DEVICEADDR: "http://${DEVICE_ID}_device-gateway:6107"
            # name of the skill that will be deployed
            SKILLS: "[\"switch\"]"
            # The API token that need to be used to authenticate user and used as cookie
            DIOTTOKEN: "Just-because-something-doesnt-do-what-you-planned-it-to-do-doesnt-mean-its-useless"
            # URL for fass swarm
            # faas_swarm_url: "http://faas-swarm:8080/"
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 20
                window: 380s
            placement:
                constraints:
                    - 'node.role == manager'
                    - 'node.platform.os == linux'
            resources:
                limits:
                    memory: 50M
#        secrets:
#            - DIOT_USER_TOKEN # It is used to register the device
                            

    # Docker Swarm provider (Required: install skills dynamically)
    faas-swarm:
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        # ports:
        #    - 8081:8080
        image:  functions/faas-swarm:0.2.7
        networks:
            - device
        environment:
            read_timeout:  "300s"   # set both here, and on your functions
            write_timeout: "300s"   # set both here, and on your functions
            DOCKER_API_VERSION: "1.30"
        deploy:
            mode: global
            placement:
                constraints:
                    - 'node.role == manager'
                    - 'node.platform.os == linux'
            resources:
                # limits:   # Enable if you want to limit memory usage
                #     memory: 100M
                reservations:
                     memory: 100M
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 20
                window: 380s

    # SKILLS : Skills that will run with the platform 
    #            > Skill can later be installed from dailyiot platform once the 
    #              device is registered
    #            > Comment the below section if you want to install seperately 
    # 
    # NOTE: 
    #  > Skill name is service name
    #  > There can be atmost 1 type of skill
    #  > There can be only one replica of a single skill
    
    switch:
        # Dummy Switch
        image: s8sg/skill-switch-dummy:1.0.0
        networks:
            - device
        deploy:
            mode: global
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 20
                window: 380s
        environment:
            # A list of GPIO pins based ordered on switch no.
            # i.e.
            # switch 1 -> gpio pin 2
            # switch 2 -> gpio pin 3
            # switch 4 -> gpio pin 17
            switch_pins: "[2, 3, 4, 17]"

networks:
    # Use docker network created fot that specific device
    device:
        external:
            name: ${DEVICE_ID}

    # For dev env (should not be on func_functions on production)
    func_functions:
        external:
            name: func_functions
