FROM golang:1.9.6 as build

WORKDIR /go/src/github.com/openfaas/faas/gateway

COPY vendor         vendor

COPY server.go      .

RUN GOARM=7 CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o gateway .

FROM alpine:3.7
WORKDIR /root/

EXPOSE 8080
ENV http_proxy      ""
ENV https_proxy     ""

COPY --from=0 /go/src/github.com/openfaas/faas/gateway/gateway    .

CMD ["./gateway"]
